data_source spark_df:
  type: spark

data_source snowflake:
  type: snowflake
  account: tu01276.ap-south-1.aws
  username: "afaque205"
  password: ${SNOWFLAKE_PASSWORD}
  warehouse: COMPUTE_WH
  database: SNOWFLAKE_SAMPLE_DATA
  schema: TPCH_SF10

# data_source databricks:
#   type: spark
#   method: databricks
#   catalog: samples
#   schema: nyctaxi
#   host: hostname_from_Databricks_SQL_settings
#   http_path: http_path_from_Databricks_SQL_settings
#   token: my_access_token
